Update test zoo
- Unify test setup in Docker files
- Add Fedora 38 Docker image
- Add OpenSUSE Leap Docker image
- Add OpenSUSE Tumbleweed Docker image
- Drop Fedora 36 Docker image
- Drop OpenSUSE 15 Docker image

Signed-off-by: Thomas Lauf <thomas.lauf@tngtech.com>

diff --git a/test/docker/alpine-edge b/test/docker/alpine-edge
--- a/test/docker/alpine-edge
+++ b/test/docker/alpine-edge
@@ -28,6 +28,7 @@ RUN make -j2
 RUN make install
 
 # Setup tests
-RUN make -j2 test || true
 WORKDIR /root/code/test/
-CMD ["bash", "-c", "./problems --summary ; cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version; exit $FAILED"]
+RUN make -j2
+
+CMD ["bash", "-c", "./run_all -v ; cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version ; exit $FAILED"]
diff --git a/test/docker/opensusetumbleweed b/test/docker/opensusetumbleweed
--- a/test/docker/opensusetumbleweed
+++ b/test/docker/opensusetumbleweed
@@ -1,18 +1,16 @@
-FROM opensuse/leap:15
+FROM opensuse/tumbleweed
 
 RUN zypper install -y \
            cmake \
-           coreutils \
            gcc-c++ \
            git \
-           make \
            man \
            python3 \
-           python3-dateutil \
+           python3-python-dateutil \
            ruby
 
 RUN gem install asciidoctor -v 2.0.15
-RUN update-alternatives --install /usr/bin/asciidoctor asciidoctor /usr/lib64/ruby/gems/2.5.0/gems/asciidoctor-2.0.15/bin/asciidoctor 10
+RUN update-alternatives --install /usr/bin/asciidoctor asciidoctor /usr/bin/asciidoctor.ruby3.2 10
 RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10
 ENV TZ=Europe/Berlin
 
@@ -33,6 +31,6 @@ RUN make install
 
 # Setup tests
 WORKDIR /root/code/test/
-RUN make
+RUN make -j2
 
-CMD ["bash", "-c", "./run_all -v ; cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version; exit $FAILED"]
+CMD ["bash", "-c", "./run_all -v ; cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version ; exit $FAILED"]
