Unify test setup in Docker files
Signed-off-by: Thomas Lauf <thomas.lauf@tngtech.com>

diff --git a/test/docker/centos7 b/test/docker/centos7
--- a/test/docker/centos7
+++ b/test/docker/centos7
@@ -34,7 +34,7 @@ RUN make -j2
 RUN make install
 
 # Setup tests
-RUN make test -j2 || true
 WORKDIR /root/code/test/
+RUN make -j2
 
-CMD ["bash", "-c", "cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version ; exit $FAILED"]
+CMD ["bash", "-c", "./run_all -v ; cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version ; exit $FAILED"]
diff --git a/test/docker/opensuse1500 b/test/docker/opensuse1500
--- a/test/docker/opensuse1500
+++ b/test/docker/opensuse1500
@@ -30,6 +30,6 @@ RUN make install
 
 # Setup tests
 WORKDIR /root/code/test/
-RUN make
+RUN make -j2
 
-CMD ["bash", "-c", "./run_all -v ; cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version; exit $FAILED"]
+CMD ["bash", "-c", "./run_all -v ; cat all.log | grep 'not ok' ; ./problems ; FAILED=$? ; echo timew $( timew --version ) ; python --version ; cmake --version ; gcc --version ; exit $FAILED"]
